WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "C:\Users\ian.hoffman\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ian.hoffman\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ian.hoffman\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 44, in autodetect
    from . import file_cache
  File "C:\Users\ian.hoffman\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 40, in <module>
    raise ImportError(
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
DEBUG:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest
DEBUG:googleapiclient.discovery:URL being requested: GET https://gmail.googleapis.com/gmail/v1/users/me/profile?alt=json
INFO:oauth2client.transport:Refreshing due to a 401 (attempt 1/2)
INFO:oauth2client.client:Refreshing access_token
INFO:root:Succesfully initializing email connection.
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "C:\Users\ian.hoffman\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ian.hoffman\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ian.hoffman\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 44, in autodetect
    from . import file_cache
  File "C:\Users\ian.hoffman\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 40, in <module>
    raise ImportError(
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
DEBUG:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest
DEBUG:googleapiclient.discovery:URL being requested: GET https://gmail.googleapis.com/gmail/v1/users/me/profile?alt=json
INFO:root:Succesfully initializing email connection.
INFO:root:Checking for new unread emails.
DEBUG:googleapiclient.discovery:URL being requested: GET https://gmail.googleapis.com/gmail/v1/users/me/threads?q=label%3AUNREAD&maxResults=25&alt=json
DEBUG:googleapiclient.discovery:URL being requested: GET https://gmail.googleapis.com/gmail/v1/users/me/threads/175f6a82f6bcdb7c?alt=json
INFO:root:New Unread Autocropping Task from: Robin.Miller@fourfrontdesign.com Recieved at 2020-11-23 12:50:17
INFO:root:Section to autocrop: \\FFDQNAP\GISProject\15-2238 USDVA SAC IDIQ for AE Services for GIS-GPS Surveys of NCs\OPY3\15.2238.082 Great Lakes National Cemetery\Data\Section005\HoldingImages\5.2\5.2-SPLIT-D
INFO:root:Assigned task number: 0
INFO:root:Atempting to send email.
Recipient: Robin.Miller@fourfrontdesign.com
Subject: Task Placed In Queue!
Body: Your request to process: 
 \\FFDQNAP\GISProject\15-2238 USDVA SAC IDIQ for AE Services for GIS-GPS Surveys of NCs\OPY3\15.2238.082 Great Lakes National Cemetery\Data\Section005\HoldingImages\5.2\5.2-SPLIT-D 
 Task has been placed in the queue. 
 You will be emailed when it completes.
DEBUG:googleapiclient.discovery:URL being requested: POST https://gmail.googleapis.com/gmail/v1/users/me/messages/send?alt=json
DEBUG:googleapiclient.discovery:URL being requested: POST https://gmail.googleapis.com/gmail/v1/users/me/threads/175f6a82f6bcdb7c/modify?alt=json
DEBUG:googleapiclient.discovery:URL being requested: GET https://gmail.googleapis.com/gmail/v1/users/me/threads/175dca840c95f5b3?alt=json
DEBUG:googleapiclient.discovery:URL being requested: GET https://gmail.googleapis.com/gmail/v1/users/me/threads/175dbe8adf11fd7d?alt=json
DEBUG:googleapiclient.discovery:URL being requested: GET https://gmail.googleapis.com/gmail/v1/users/me/threads/175b7d7f01835da3?alt=json
DEBUG:googleapiclient.discovery:URL being requested: GET https://gmail.googleapis.com/gmail/v1/users/me/threads/175a45ce7a99b047?alt=json
INFO:root:Autocropping: \\FFDQNAP\GISProject\15-2238 USDVA SAC IDIQ for AE Services for GIS-GPS Surveys of NCs\OPY3\15.2238.082 Great Lakes National Cemetery\Data\Section005\HoldingImages\5.2\5.2-SPLIT-D
INFO:root:Atempting to send email.
Recipient: Robin.Miller@fourfrontdesign.com
Subject: Task Has Completed Succesfully!
Body: Section: 
 \\FFDQNAP\GISProject\15-2238 USDVA SAC IDIQ for AE Services for GIS-GPS Surveys of NCs\OPY3\15.2238.082 Great Lakes National Cemetery\Data\Section005\HoldingImages\5.2\5.2-SPLIT-D 
 Has completed succesfully. 
 If you have additional items in the queue you will be emailed separately.
DEBUG:googleapiclient.discovery:URL being requested: POST https://gmail.googleapis.com/gmail/v1/users/me/messages/send?alt=json
